name = "rsh-flywheel"
main = "src/worker.ts"
compatibility_date = "2025-09-01"
workers_dev = true

[vars]
RPC_URL = ""
DEV_WALLET = ""
TOKEN_MINT = ""
TX_FEE_BUFFER = "0.01"
PUMPPORTAL_API = "https://pumpportal.fun/api/v2"
PUMPPORTAL_LIGHTNING = "true"
JUPITER_API = "https://quote-api.jup.ag/v6"
SLIPPAGE_BPS = "100"
MIN_BUY_SOL = "0.02"
MAX_BUY_SOL = "5"
BURN_METHOD = "incinerator"
DRY_RUN = "false"

[triggers]
crons = ["*/20 * * * *"]
